### ISSUE TITLE
Demo app appears to be down

### ISSUE THREAD

**Issue by avidrucker** [learning-toolbox/viridi#1]
When I visit https://viridi-vite-demo.netlify.app/ I get a page that says "Site Not Found - Looks like you've followed a broken link or entered a URL that doesn't exist on Netlify."

**Comment by ChrisShank** [comment]
I think i deleted the demo a while back as I stopped working on this project. If you clone the repo you *should* be able to play around with it. Looking for anything in particular?

**Comment by avidrucker** [comment]
I was curious to see if there was a quick demo to see, and wanted to make sure the demo wasn't down in error. Thank you for the quick response!
